# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY scripts/install-build.sh /scripts/install-build.sh

RUN chmod +x /scripts/install-build.sh

# RUN ./scripts/install-build.sh

EXPOSE 9559

CMD ["npm", "prodstart"]